<?php

namespace Database\Seeders;

use App\Models\Informasi;
use Illuminate\Database\Seeder;

class InformasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $informasi =  [
            [
                'judulInformasi' => 'Kelebihan Konsumsi Suplemen Vitamin E Picu Kanker Prostat',
                'excerptJudul' => 'Kelebihan Konsumsi Suplemen Vitamin E Picu Kanker Prostat',
                'excerptBody' => 'Studi mengungkapkan bahwa suplemen tertentu memiliki efek samping yang berbahaya bagi tubuh. Efek samping tersebut bisa membuat seseorang terkena kanker. Dilansir dari dailyrecord, pada Senin (22/11), penelitian yang diterbitkan dalam Journal of National Cancer Institute menunjukkan bahwa beberapa vitamin dan mineral yang populer bisa memicu penyakit.',
                'text1' => '<p class="text-justify fs-6 mt-5">Studi mengungkapkan bahwa suplemen tertentu memiliki efek samping yang berbahaya bagi tubuh. Efek samping tersebut bisa membuat seseorang terkena kanker. Dilansir dari dailyrecord, pada Senin (22/11), penelitian yang diterbitkan dalam Journal of National Cancer Institute menunjukkan bahwa beberapa vitamin dan mineral yang populer bisa memicu penyakit.</p><p class="text-justify fs-6 mt-2">“Secara khusus, ditemukan bahwa selenium dan vitamin E dapat meningkatkan kemungkinan kanker prostat tingkat tinggi hingga 91 persen. Pria yang menggunakan suplemen ini harus berhenti. Baik suplemen selenium maupun vitamin E tidak memberikan manfaat, yang diketahui hanya risiko," kata Ilmuwan Alan Kristal dari Pusat Penelitian Kanker Fred Hutchinson di Seattle.</p><p class="text-justify fs-6 mt-2">Ia mengatakan, masyarakat cukup sering disesatkan untuk percaya bahwa suplemen kesehatan bermanfaat sehingga masyarakat konsumsi secara terus menerus. Menurutnya, ini tidak benar. Dari beberapa penelitian lain mengungkapkan bahwa beberapa suplemen makanan dosis tinggi, yaitu suplemen yang menyediakan jauh lebih banyak asupan mikronutrien harian yang direkomendasikan bisa meningkatkan risiko kanker. “Kami mengetahui hal ini berdasarkan studi acak terkontrol, tersamar ganda untuk folat dan beta karoten.',
                'text2' => '<p class="text-justify fs-6 mt-2">Sekarang kami mengetahuinya, itu adalah vitamin E dan selenium," kata dia. Penelitian secara khusus menemukan bahwa selenium dan vitamin E dapat meningkatkan risiko kanker prostat tingkat tinggi hingga 91 persen. Para peneliti terpaksa menghentikan percobaan setelah menemukan dampak negatif selenium dosis tinggi. </p><p class="text-justify fs-6 mt-2">Selain itu, para peneliti percaya beberapa suplemen tidak menawarkan manfaat apapun. Selama uji coba, para peneliti juga menemukan vitamin E dapat merugikan, khususnya vitamin E yang bisa meningkatkan risiko kanker agresif. Penelitian ini dilakukan pada lebih dari 35 ribu pria untuk mengevaluasi efek perlindungan kanker dari suplemen. Temuan mengungkapkan bahwa selenium tidak menimbulkan risiko bagi individu yang kekurangan mineral. Tetapi, ketika dikonsumsi oleh individu yang kadarnya sudah tinggi, risiko kanker tingkat tinggi naik hingga 91 persen.</p><p class="text-justify fs-6 mt-2">Para peneliti juga menemukan, individu dengan selenium tinggi pada awal penelitian yang mengonsumsi suplemen vitamin E, mengalami peningkatan risiko kanker prostat sebesar 69 persen dan risiko kanker tingkat tinggi meningkat sebesar 111 persen </p></p>'
            ],
            [
                'judulInformasi' => 'Benarkah Diet Bertujuan untuk Menurunkan Berat Badan? Berikut Ulasan Dokter',
                'excerptJudul' => 'Benarkah Diet Bertujuan untuk Menurunkan Berat Badan? Be..',
                'excerptBody' => 'Diet yang biasa kita pahami adalah mengurangi makanan. Banyak yang beranggapan bahwa diet adalah pola makan dengan cara mengurangi porsi dan jenis makanan yang dikonsumsi. Padahal, sebenarnya menjalankan diet lebih dari kedua poin tersebut. Saat ini banyak sekali diet yang beredar di masyarakat dengan tujuan untuk menurunkan berat badan. Beberapa jenis diet mungkin mem..',
                'text1' => '<p class="text-justify fs-6 mt-5"> Diet yang biasa kita pahami adalah mengurangi makanan. Banyak yang beranggapan bahwa diet adalah pola makan dengan cara mengurangi porsi dan jenis makanan yang dikonsumsi. Padahal, sebenarnya menjalankan diet lebih dari kedua poin tersebut. Saat ini banyak sekali diet yang beredar di masyarakat dengan tujuan untuk menurunkan berat badan. Beberapa jenis diet mungkin mempengaruhi perubahan berat badan seseorang, tetapi akan berdampak pada penurunan kesehatan akibat turunnya berat badan secara drastis. Pengertian diet sebetulnya adalah makan.</p><p class="text-justify fs-6 mt-2"> Diet adalah pola makan dengan mengonsumsi makanan yang cara dan sumber makanannya telah diatur. Tujuan mengatur cara mengonsumsi makanan dan sumber makanan adalah untuk menjaga kesehatan tubuh secara keseluruhan. Diet bertujuan untuk mencapai ataupun menjaga berat badan agar terkontrol.Kerap kali seseorang yang merasa dirinya terlalu gemuk akan melakukan diet.</p><p class="text-justify fs-6 mt-2">Tentu saja tidak semua diet dilakukan untuk menurunkan beart badan, pada beberapa orang melakukan diet atas anjuran dokter karena menderita penyakit tertentu dan memaksanya untuk mengatur nutrisi yang masuk ke tubuh. </p>',
                'text2' => '<p class="text-justify fs-6 mt-2"> Jika ingin menurunkan berat badan tentu saja harus melakukan diet yang sehat. Namun diet sehat tidak hanya untuk menurunkan berat badan, namun untuk menjaga metabolisme tubuh agar tetap sehat, dan baik. Sebetulnya diet sehat bukan hanya untuk seseorang yang ingin menurunkan berat badan, tetapi diet sehat sangat baik untuk orang yang tidak dalam proses menurunkan berat badan.</p><p class="text-justify fs-6 mt-2">Untuk mengetahui metabolisme tubuh yang paling mudah adalah dari tubuh kita sendiri, apakah kita merasa fit, mudah lelah, mudah pusing dan merasa pegal-pegal. Jika ingin mengetahui kondisi metbolisme tubuh lebih lanjut diperlukan periksa tekanan darah, periksa lab seperti cek kadar gula dan kolesterol. Apabila ingin cek kondisi tubuh secara lengkap bisa langsung ke dokter. Tetapi kita juga bisa mengenali kondisi tubuh apakah sedang baik-baik saja atau tidak. </p><p class="text-justify fs-6 mt-2"> Ini disampaikan pada channel YouTube KompasTV, bersama dengan dr. Syahidatul Wafa, Sp.PD. Seorang dokter spesialis penyakit dalam. Minggu (26/9/2021) </p>'
            ],
            [
                'judulInformasi' => 'Khasiat Ketumbar, Turunkan Kolesterol Hingga Baik untuk Diabetes',
                'excerptJudul' => 'Khasiat Ketumbar, Turunkan Kolesterol Hingga Baik untuk..',
                'excerptBody' => 'Ketumbar menjadi salah satu bumbu dapur yang ternyata memiliki manfaat bagi kesehatan tubuh. Ketumbar memiliki kandungan protein, lemak, magnesium, kalsium, kalium, dan karbohidrat. Kandungan tersebut sangat efektif untuk menjaga kesehatan tubuh.',
                'text1' => '<p class="text-justify fs-6 mt-5"> Ketumbar menjadi salah satu bumbu dapur yang ternyata memiliki manfaat bagi kesehatan tubuh. Ketumbar memiliki kandungan protein, lemak, magnesium, kalsium, kalium, dan karbohidrat. Kandungan tersebut sangat efektif untuk menjaga kesehatan tubuh. </p><p class="text-justify fs-6 mt-2"> Selain itu, ketumbar disebut-sebut memiliki manfaat untuk menurunkan kolesterol, gangguan fungsi jantung dan diabetes. Benarkah demikian? Hal tersebut ternyata dibenarkan oleh Ahli herbal dr.Muthoharoh,M.Si dalam program Hidup Sehat TvOne </p><p class="text-justify fs-6 mt-2"> "Fakta memang sudah digunakan sampai sekarang, pengobatan Arab dan Maroko," kata Muthe, Senin 22 November 2021. Dijelaskan Muthe, ketumbar berfungsi membantu menurunkan kadar LDL sehingga baik untuk kesehatan jantung. Karena, kata dia LDL yang berlebih pada seseorang berisiko terjadinya plak. </p>',
                'text2' => '<p class="text-justify fs-6 mt-2"> Nantinya, penumpukan plak ini akan membuat darah kesulitan mengalir melalui arteri karena arteri yang mengalami penyempitan termasuk arteri yang mengarah ke jantung. "Memiliki efek vasodilator, melebarkan pembuluh darah sehingga baik untuk penderita hipertensi," kata dia. Lebih lanjut, Muthe menjelaskan bahwa ketumbar ini juga berfungsi untuk membantu menurunkan kadar gula darah, lantaran ketumbar ini bersifat seperti insulin. </p><p class="text-justify fs-6 mt-2"> "Memiliki efek diuretik memperbanyak pengeluaran urin. Bagi mereka yang diabetes konsumsi obat rutin gula dijarak dua jam tidak berbarengan," kata Muthe. Lantas bagaimana cara mengonsumsi ketumbar untuk menurunkan kolesterol, gangguan fungsi jantung dan diabetes? </p><p class="text-justify fs-6 mt-2"> Cukup siapkan 2 sdm ketumbar utuh. Lalu seduh dengan segelas air panas. Setelah diseduh dengan air panas dan diamkan selama 15 menit dengan menutup gelas. Hal ini bertujuan agar minyak atsiri tidak ikut menguap. </p>'
            ],
            [
                'judulInformasi' => 'Manfaat Daun Pepaya untuk Kesehatan, Tak Sekadar Pahit',
                'excerptJudul' => 'Manfaat Daun Pepaya untuk Kesehatan, Tak Sekadar Pahit',
                'excerptBody' => 'Pepaya merupakan buah yang kaya antioksidan, vitamin, mineral, dan enzim yang dapat membantu melancarkan sistem pencernaan. Selain itu, daunnya pun mengandung protein, serat, kalsium hingga vitamin B1, B3, B3 hingga vitamin C. Mengutip dari laman Healthline, manfaat d..',
                'text1' => '<p class="text-justify fs-6 mt-5">Pepaya merupakan buah yang kaya antioksidan, vitamin, mineral, dan enzim yang dapat membantu melancarkan sistem pencernaan. Selain itu, daunnya pun mengandung protein, serat, kalsium hingga vitamin B1, B3, B3 hingga vitamin C. </p><p class="text-justify fs-6 mt-2">Mengutip dari laman Healthline, manfaat daun pepaya yaitu:</p><h4 class="fs-5">1. Mengobati gejala demam berdarah</h4><p class="text-justify fs-6 mt-2">Salah satu manfaat yang paling menonjol dari daun pepaya adalah untuk mengobati gejala tertentu yang berhubungan dengan penyakit ini. Daun pepaya pun secara signifikan meningkatkan kadar trombosit darah dalam tubuh. Demam berdarah merupakan virus yang ditularkan oleh nyamuk yang dapat menular ke manusia dan menimbulkan gejala seperti flu, demam, kelelahan, sakit kepala, mual, muntah, dan ruam kulit. </p><h4 class="fs-5">2. Meningkatkan gula darah</h4><p class="text-justify fs-6 mt-2">Daun pepaya sering digunakan dalam pengobatan masyarakat Meksiko sebagai terapi alami untuk mengobati diabetes dan meningkatkan kontrol gula darah. Hal ini karena kemampuan daun pepaya untuk melindungi sel-sel penghasil insulin di pankreas dari kerusakan dan kematian dini. </p><h4 class="fs-5"> 3. Mendukung fungsi pencernaan</h4><p class="text-justify fs-6 mt-2">Teh dan ekstrak daun pepaya sering digunakan sebagai terapi alternatif untuk meringankan gejala pencernaan yang tidak baik, seperti gas, kembung , dan mulas. Hal ini karena daun pepaya mengandung serat dan nutrisi yang mendukung fungsi pencernaan yang sehat dan senyawa unik yang disebut papain. </p>',
                'text2' => '<h4 class="fs-5"> 4. Memiliki efek anti inflamasi</h4><p class="text-justify fs-6 mt-2">Daun pepaya sering digunakan untuk mengobati berbagai kondisi peradangan internal dan eksternal, termasuk ruam kulit, nyeri otot, dan nyeri sendi. Hal ini karena daun pepaya mengandung berbagai nutrisi dan senyawa tanaman dengan manfaat anti-inflamasi, seperti papain, flavonoid, dan vitamin E. </p><h4 class="fs-5"> 5. Mendukung pertumbuhan rambut</h4><p class="text-justify fs-6 mt-2">Aplikasi topikal dari masker dan jus daun pepaya sering digunakan untuk meningkatkan pertumbuhan rambut dan kesehatan kulit kepala. Beberapa penelitian menunjukkan bahwa tingkat stres oksidatif yang tinggi dalam tubuh dapat menyebabkan kerontokan rambut. Makan makanan kaya antioksidan dapat membantu mengurangi stres oksidatif dan selanjutnya meningkatkan pertumbuhan rambut.</p><h4 class="fs-5"> 6. Menjaga kulit tetap sehat</h4><p class="text-justify fs-6 mt-2">Daun pepaya sering dikonsumsi atau dioleskan sebagai cara untuk menjaga kulit tetap lembut, bersih, dan tampak awet muda . Enzim pelarut protein dalam daun pepaya yang disebut papain dapat digunakan secara topikal sebagai exfoliant untuk mengangkat sel kulit mati dan berpotensi mengurangi terjadinya pori-pori tersumbat, rambut tumbuh ke dalam, dan jerawat. </p><h4 class="fs-5"> 7. Memiliki sifat antikanker</h4><p class="text-justify fs-6 mt-2">Daun pepaya telah digunakan dalam praktik pengobatan tradisional untuk mencegah dan mengobati jenis kanker tertentu. Ekstrak daun pepaya telah menunjukkan kemampuan yang kuat untuk menghambat pertumbuhan sel kanker prostat dan payudara dalam penelitian tabung reaksi. </p>'
            ],
            [
                'judulInformasi' => 'Makanan yang Baik Dikonsumsi oleh Pasien Penyakit Jantung',
                'excerptJudul' => 'Makanan yang Baik Dikonsumsi oleh Pasien Penyakit Jantung',
                'excerptBody' => 'Penyakit jantung dikenal memang bisa sangat berbahaya, bahkan bisa menyebabkan kematian. Meskipun demikian, bukan berarti mereka yang memiliki diagnosis dengan penyakit jantung tidak bisa memiliki umur yang panjang dan kehidupan yang sehat',
                'text1' => '<p class="text-justify fs-6 mt-5"> Penyakit jantung dikenal memang bisa sangat berbahaya, bahkan bisa menyebabkan kematian. Meskipun demikian, bukan berarti mereka yang memiliki diagnosis dengan penyakit jantung tidak bisa memiliki umur yang panjang dan kehidupan yang sehat. Dengan olahraga yang cukup, diet yang tepat, dan perawatan medis rutin, pasien dapat mengelola penyakit jantung dan berpotensi mengurangi risiko kejadian kesehatan yang merugikan di kemudian. </p><p class="text-justify fs-6 mt-2">Dikutip dari Eat This, berikut ini adalah makanan yang baik untuk pasien penyakit jantung: </p><h4 class="fs-6 mt-2">Oatmeal</h4><p class="text-justify fs-6 mt-2"> Oatmeal sering menjadi pilihan yang mudah ketika ingin sarapan yang sehat dan mengenyangkan. Amy Goodrich, MS, RD, pemilik Leading Edge Nutrition, LLC, mengatakan bahwa oat adalah pilihan tepat bagi pasien penyakit jantung. "Oat adalah gandum utuh dan sumber serat yang baik. Serat larut dalam gandum membantu mengurangi penyerapan LDL atau kolesterol jahat dalam aliran darah," kata Goodrich. </p>',
                'text2' => '<h4 class="fs-6 mt-2">Kacang-kacangan</h4><p class="text-justify fs-6 mt-2"> Meskipun kacang mungkin tinggi lemak, para ahli mengatakan bahwa kacang masih aman dikonsumsi, sekalipun bagi mereka yang punya penyakit jantung. "Kacang adalah sumber antioksidan, lemak sehat, dan serat. Mengonsumsi beberapa porsi per minggu menurunkan kolesterol dan mengurangi peradangan dalam tubuh," kata Tina Marinaccio, MS, RD, CPT, pendiri Health Dynamics, LLC.Namun, Marinaccio merekomendasikan untuk tidak mengonsumsinya berlebihan. "Karena kandungan lemaknya, kacang-kacangan tinggi kalori, jadi pastikan untuk mengukur porsinya," jelasnya.</p><h4 class="fs-6 mt-2">Buah berry</h4><p class="text-justify fs-6 mt-2"> Makanan penutup tidak harus dihilangkan bagi pasien penyakit jantung, tetapi harus bijaksana dalam melakukan pemilihannya. Itu sebabnya Colleen Christensen, RD, pendiri Colleen Christensen Nutrition, merekomendasikan untuk menambahkan buah beri ke dalam diet sehari-hari."Buah berry adalah sumber antioksidan pelindung dan fitokimia yang berhubungan dengan kesehatan jantung," jelas Christensen. </p><h4 class="fs-6 mt-2">Kacang kedelai utuh</h4><p class="text-justify fs-6 mt-2"> Laura Yautz, RDN, LDN, NBC-HWC, seorang ahli diet mengatakan bahwa menambahkan beberapa produk kedelai yang belum diproses ke dalam rencana makanan dapat menjadi pilihan yang bagus untuk orang dengan penyakit jantung. "Kedelai yang tidak diproses tinggi protein, serat, lemak sehat, dan antioksidan yang dapat membantu menurunkan tekanan darah, kolesterol, trigliserida, dan peradangan," jelas Yautz. </p><h4 class="fs-6 mt-2">Ikan berlemak</h4><p class="text-justify fs-6 mt-2"> Goodrich mengatakan bahwa memasukkan ikan berlemak ke dalam diet sehari-hari dapat menjadi cara yang bagus untuk meningkatkan kesehatan kardiovaskular."Ikan berlemak seperti salmon dan tuna adalah sumber asam lemak omega-3 yang sangat baik. Makan ikan dua kali seminggu dapat membantu menurunkan trigliserida, tekanan darah, dan kolesterol total di mana semuanya merupakan penanda penyakit jantung," tutur Goodrich.</p>'
            ],
            [
                'judulInformasi' => '3 Cara Menurunkan Berat Badan tanpa Diet Ketat Menurut Ahli Gizi',
                'excerptJudul' => '3 Cara Menurunkan Berat Badan tanpa Diet Ketat Menurut Ahli Gizi',
                'excerptBody' => 'Menurunkan berat badan merupakan perjuangan berat bagi sebagian orang. Dari olahraga sampai diet ketat, semua di lakukan untuk mencapainya. Tapi, para ahli diet mengatakan bahwa penurunan berat badan seharusnya tidak menyiksa, apalagi sampai mengorbankan kesehatan.',
                'text1' => '<p class="text-justify fs-6 mt-2"> Menurunkan berat badan merupakan perjuangan berat bagi sebagian orang. Dari olahraga sampai diet ketat, semua di lakukan untuk mencapainya. Tapi, para ahli diet mengatakan bahwa penurunan berat badan seharusnya tidak menyiksa, apalagi sampai mengorbankan kesehatan. </p><p class="text-justify fs-6 mt-2"> Proses itu bisa dilakukan dengan mengubah pola makan dan memperkenalkan kebiasaan makan yang lebih bersih dengan sesekali punya cheat day.  </p><p class="text-justify fs-6 mt-2"> Dilansir dari Indian Express, Rabu, 24 November 2021, ahli gizi India Azra Khan membagikan tiga cara cerdas di mana seseorang bisa mendapatkan berat badan yang diinginkan, tanpa melakukan sesuatu yang terlalu dramatis. </p><p class="text-justify fs-6 mt-2"> Khan mengatakan seseorang dapat menciptakan defisit kalori dalam makanan mereka tanpa mengorbankan apa yang mereka makan. Defisit kalori pada dasarnya adalah kekurangan jumlah kalori yang dikonsumsi seseorang, dibandingkan dengan jumlah kalori yang dibutuhkan untuk mempertahankan berat badan saat ini.</p>',
                'text2' => '<p class="text-justify fs-6 mt-2"> Berikut adalah beberapa cara jitu untuk menurunkan berat badan tanpa diet ketat menurut Khan.</p><h4 class="fs-5>1. Latihan beban</h4><p class="text-justify fs-6 mt-2"> Ahli gizi menyarankan bahwa proses ini akan membantu meningkatkan metabolisme dengan meningkatkan otot.</p><h4 class="fs-5>2. Intermittent fasting</h4><p class="text-justify fs-6 mt-2"> Menjadi hit di antara orang-orang yang sadar kebugaran dan kesehatan, puasa intermiten atau intermittent fasting melibatkan puasa untuk jangka waktu tertentu setelah makan makanan sehat. </p><p class="text-justify fs-6 mt-2"> Prinsip dasarnya adalah memberi tubuh waktu untuk mencerna makanan, membakar kelebihan lemak tubuh dan detoksifikasi. Itu dianggap lebih selaras dengan ritme sirkadian tubuh. </p><h4 class="fs-5>3. Makan 1 g protein per kg berat badan</h4><p class="text-justify fs-6 mt-2"> Pakar menyarankan agar makan lebih banyak protein dalam diet agar bisa tetap kenyang lebih lama. </p>'
            ],
            [
                'judulInformasi' => '9 Cara Mengatasi Asam Lambung  Naik Tanpa Minum Obat',
                'excerptJudul' => '9 Cara Mengatasi Asam Lambung  Naik Tanpa Minum Obat',
                'excerptBody' => 'Salah satu penyakit yang mudah kumat dan kerap menyerang adalah asam lambung. Namun, cara mengatasi asam lambung naik juga bisa Anda siapkan untuk menghindari risiko pe..',
                'text1' => '<p class="text-justify fs-6 mt-2">Salah satu penyakit yang mudah kumat dan kerap menyerang adalah asam lambung. Namun, cara mengatasi asam lambung naik juga bisa Anda siapkan untuk menghindari risiko penyakit bertambah parah. Penyakit asam lambung juga dikenal dengan nama astroesophageal reflux disease (GERD) yang membuat penderitanya merasa terbakar di dada akibat asam lambung naik ke kerongkongan. Gejala penyakit asam lambung umumnya muncul minimal dua kali dalam seminggu.</p><p class="text-justify fs-6 mt-2">Penyakit ini bisa menyerang siapapun tanpa memandang usia atau jenis kelamin dari anak-anak hingga orang dewasa. Gejala penyakit ini sering diduga sebagai serangan jantung atau penyakit jantung koroner, karena gejalanya yang hampir mirip dengan nyeri dada. Meskipun tidak mematikan seperti serangan jantung, penyakit asam lambung perlu ditangani agar tidak menimbulkan komplikasi.</p><p class="text-justify fs-6 mt-2">Bagi mereka yang mengalami asam lambung, akan mengalami gejala rasa seperti terbakar di dada (heartburn), yang bertambah parah setelah makan atau saat berbaring. Gejala ini juga kerap disertai dengan keluhan gangguan pencernaan lainnya, seperti sering bersendawa, mual dan muntah, serta maag dan sesak napas. Penyakit asam lambung juga dapat menimbulkan keluhan mulut terasa asam.Adapun penyebab asam lambung menjadi naik karena proses otot kerongkongan bagian bawah (otot LES) melemah. Tak jarang, gejala asam lambung turut menjalar hingga ke kerongkongan atau yang dikenal refluks asam lambung. </p><p class="text-justify fs-6 mt-2">Pengaruh otot LES bisa menyebabkan kontraksi dan menutup saluran ke kerongkongan setelah makanan turun ke lambung. Bila otot ini lemah, kerongkongan akan tetap terbuka dan asam lambung naik kembali ke kerongkongan. Hal ini perlu diawasi secara cermat, karena berisiko terjadi pada orang lanjut usia (lansia), orang dengan obesitas, perokok, orang yang sering berbaring atau tidur setelah makan, serta wanita hamil.</p><p class="text-justify fs-6 mt-2">Ada sejumlah cara mengatasi asam lambung naik, salah satunya dengan menggunakan antasida sebagai obat yang sering dicari. Antasida dinilai ampuh untuk meredakan asam lambung dengan cepat. Pada kasus asam lambung yang lebih parah, pilihan obat dengan resep dokter mungkin diperlukan untuk mencegah kerusakan pada kerongkongan.</p><p class="text-justify fs-6 mt-2">Namun, antasida berpotensi menjadikan penderita asam lambung menjadi kecanduan terhadap obat satu ini. Dilansir dari situs informasi kesehatan Halodoc.com, ada sejumlah cara untuk mengatasi asam lambung.</p>',
                'text2' => '<p class="text-justify fs-6 mt-2">Cara Menurunkan Asam Lambung yang Naik :</p><h4 class="fs-5">1. Jauhi makanan pemicu refluks</h4><p class="text-justify fs-6 mt-2">Cara mengatasi asam lambung naik adalah dengan menghindari makanan tertentu yang memicu mulas, seperti kafein, soda, cokelat, buah dan jus jeruk, tomat, bawang, mint dan makanan berlemak tinggi.</p><h4 class="fs-5">2. Konsumsi makanan dengan kandungan banyak serat</h4><p class="text-justify fs-6 mt-2">Khasiat serat salah satunya adalah untuk membantu saluran pencernaan bekerja dengan lancar dan sehat.</p><h4 class="fs-5">3. Mengatur jadwal porsi makan</h4><p class="text-justify fs-6 mt-2">Salah satu cara mengatasi asam lambung naik, yakni dengan menghindari makan dalam porsi besar sekaligus. Cobalah makan lima atau enam porsi kecil sehari.</p><h4 class="fs-5">4. Pantang makan sebelum tidur</h4><p class="text-justify fs-6 mt-2">Salah satu kebiasaan yang membuat asam lambung nudah naik adalah makan sebelum tidur. Aktivitas kurang baik satu ini, sering menjadi penyebab naiknya asam lambung. Berhenti makan setidaknya dua atau tiga jam sebelum tidur, sehingga perut memiliki kesempatan untuk mengosongkannya sebelum Anda berbaring atau tidur.</p><h4 class="fs-5">5. Mengunyah makanan secara perlahan</h4><p class="text-justify fs-6 mt-2">Praktik cara mengatasi asam lambung naik satu ini terdengar ringan, namun sering disepelekan. Padahal dampaknya sangat baik untuk mencegah asam lambung naik.</p><h4 class="fs-5">6. Jauhi rokok</h4><p class="text-justify fs-6 mt-2">Kebiasaan merokok bisa mengurangi efektivitas otot yang menjaga asam di lambung. Jadi, berhenti merokok bisa menjadi salah satu cara mengatasi asam lambung naik atau kambuh.</p><h4 class="fs-5">7. Kenakan pakaian longgar dan tidak ketat</h4><p class="text-justify fs-6 mt-2">Menggunakan pakaian yang longgar bisa menghindari Anda dari risiko mengalami tekanan tambahan pada perut. Langkah ini dijuga dinilai efektif sebagai cara mengatasi asam lambung naik.</p><h4 class="fs-5">8. Mengatur poisis tidur</h4><p class="text-justify fs-6 mt-2">Pada saat tidur, Anda bisa menambahkan beberapa bantal di bagian kepala tempat tidur. Tambahan bantal dilakukan agar posisi kepala lebih tinggi sekitar enam inci. Langkah ini dinilai cukup ampuh sebagai cara mengatasi asam lambung naik</p><h4 class="fs-5">9. Mengunyah permen karet</h4><p class="text-justify fs-6 mt-2">Aktivitas sepele ini juga dinilai mampu menjadi cara mengatasi asam lambung naik. Dengan mengunyah permen karet, maka dapat meningkatkan produktivitas air liur dalam sistem pencernaan, sehingga memudahkan kinerja lambung saat memproses makanan yang masuk ke tubuh.</p><p class="text-justify fs-6 mt-2">Demikianlah cara mengatasi asam lambung tanpa harus meminum obat dan bisa dilakukan di rumah dengan mudah. Selain itu apabila penyakit asam lambung masih belum menunjukkan adanya perubahan menuju sembuh, maka sangat dianjurkan untuk berkonsultasi dengan dokter.</p>'
            ],
            [
                'judulInformasi' => 'Meski Bermanfaat, Waspadai 4  Hal dari Kacang Hijau',
                'excerptJudul' => 'Meski Bermanfaat, Waspadai 4  Hal dari Kacang Hijau',
                'excerptBody' => 'Jika kamu sedang mengonsumsi obat pengencer darah seperti warfarin, bicarakan dulu dengan dokter sebelum menambahkan kacang hijau ke dalam akanan. Pasalnya, kandungan vitamin K dari kacang-kacangan dapat mengganggu pengobatan, memengaruhi bagaimana darah kamu membeku.',
                'text1' => '<p class="text-justify fs-6 mt-2">Banyak penelitian menunjukan banyak mengonsumsi makanan nabati, salah satunya kacang hijau, membantu meningkatkan kesehatan dan mengurangi risiko penyakit kronis.Kacang hijau penuh dengan antioksidan, termasuk vitamin C, flavonol, quercetin, dan kaemferol. Antioksidan ini melawan radikal bebas dalam tubuh, yang membantu mengurangi kerusakan sel serta dapat membantu menurunkan risiko kondisi kesehatan tertentu. </p><p class="text-justify fs-6 mt-2">Tapi, pada suatu kondisi tertentu, kamu harus mewaspadai konsumsi kacang hijau seperti dilansir dari WebMD berikut ini.Sebagaimana disebutkan dalam laman tersebut, meskipun kacang hijau merupakan makanan bergizi berprotein tinggi, ada beberapa hal yang harus diperhatikan.</p><h4 class="fs-5">Dapat mengganggu pengencer darah </h4><p class="text-justify fs-6 mt-2">Jika kamu sedang mengonsumsi obat pengencer darah seperti warfarin, bicarakan dulu dengan dokter sebelum menambahkan kacang hijau ke dalam akanan. Pasalnya, kandungan vitamin K dari kacang-kacangan dapat mengganggu pengobatan, memengaruhi bagaimana darah kamu membeku.</p><h4 class="fs-5">Mengandung lektin</h4><p class="text-justify fs-6 mt-2">Lektin mengandung sejenis protein yang terdapat dalam berbagai jenis kacang-kacangan, termasuk kacang hijau. Meskipun mereka memiliki beberapa manfaat, mereka juga dapat menyebabkan ketidaknyamanan pencernaan. Untuk menonaktifkan lektin, kamu perlu memasak kacang hijau secara menyeluruh.</p>',
                'text2' => '<h4 class="fs-5">Mengandung asam fitat</h4><p class="text-justify fs-6 mt-2">Asam fitat dapat mengikat mineral tertentu, mencegah tubuh kamu menyerapnya. Jika memiliki kekurangan mineral, segera bicara dengan dokter sebelum menambahkan kacang hijau ke menu makanan.</p><h4 class="fs-5">Mungkin mengandung tambahan garam</h4><p class="text-justify fs-6 mt-2">Kacang hijau merupakan makanan rendah sodium alami. Namun, tinjauan WebMD varietas kacang hijau kalengan tertentu telah menambahkan garam. Dan disebutkan juga terlalu banyak garam dapat meningkatkan risiko tekanan darah tinggi dan masalah yang berhubungan dengan jantung. Jika membeli kacang kalengan, pastikan untuk membilasnya secara menyeluruh untuk menghilangkan kelebihan garam.</p><h4 class="fs-5">Efek samping</h4><p class="text-justify fs-6 mt-2">Riset yang dilakukan ilmuwan dari Arizona State University di Phoenix membuktikan, terlalu banyak komsumsi kacang hijau bisa memicu kembung. Menurut peneliti, penumpukan gas terjadi karena peningkatan serat makanan. Kacang hijau juga bisa bereaksi dengan obat-obatan tetentu yang mengakibatkan obat tidak bisa berfungsi maksimal. Bahkan, reaksi kacang hijau dengan obat tertentu bisa memicu diare. Konsultasikan pada dokter jika timbul rasa yang tak nyaman setelah mengonsumsi kacang hijau ini.</p>'
            ],
            [
                'judulInformasi' => ' Gejala Infeksi Para-paru yang Perlu Diwaspadai',
                'excerptJudul' => ' Gejala Infeksi Para-paru yang Perlu Diwaspadai',
                'excerptBody' => 'Infeksi paru-paru disebabkan mikroorganisme macam bakteri, virus, dan jamur. Bronkitis, pneumonia, dan bronkiolitismerupakan jenis infeksi pada paru yang umum terjadi akibat serangan mikroorganisme tersebut. Dilansir dari Health Line,mikroorganisme yang paling umum dan bertanggungjawab pada bronkitis meliputi virus influenza atau respiratory syncytialvirus (RSV), serta bakteri seperti Mycoplasma pneumonia, Chlamydia pneumonia, dan Bordetella pertussis.</p><p class="text-justify fs-6 mt-2">Infeksi paru-paru seperti pneumonia biasanya ringan tetapi bisa serius, terutama bagi orang dengan sistem kekebalan lemahatau kondisi kronis, seperti penyakit paru obstruktif kronik (PPOK). Gejala infeksi paru-paru bervariasi dari ringan hingga berat,tergantung pada beberapa faktor, termasuk usia dan kondisi kesehatan.Gejala yang ditimbulkan juga tergantung padapenyebab infeksi, apakah disebabkan oleh virus, bakteri, atau jamur. Gejalanya mungkin mirip dengan pilek atau flu tetapicenderung bertahan lebih lama. Simak 10 gejala infeksi paru-paru berikut.</p><h4 class="fs-5">Batuk dengan lendir kental</h4><p class="text-justify fs-6 mt-2">Batuk membantu membersihkan tubuh dari lendir yang dihasilkan dari peradangan saluran udara danparu-paru. Lendir ini mungkin juga mengandung darah. Penderita bronkitis atau pneumonia akan mengalami batuk yang menghasilkan lendir kental dan mungkin berwarna berbeda, seperti jernih, putih, hijau, dan abu-abu kekuningan. Batuk dapatbertahan selama beberapa minggu, bahkan setelah gejala lain membaik.',
                'text1' => '<p class="text-justify fs-6 mt-2">Infeksi paru-paru disebabkan mikroorganisme macam bakteri, virus, dan jamur. Bronkitis, pneumonia, dan bronkiolitismerupakan jenis infeksi pada paru yang umum terjadi akibat serangan mikroorganisme tersebut. Dilansir dari Health Line,mikroorganisme yang paling umum dan bertanggungjawab pada bronkitis meliputi virus influenza atau respiratory syncytialvirus (RSV), serta bakteri seperti Mycoplasma pneumonia, Chlamydia pneumonia, dan Bordetella pertussis.</p><p class="text-justify fs-6 mt-2">Infeksi paru-paru seperti pneumonia biasanya ringan tetapi bisa serius, terutama bagi orang dengan sistem kekebalan lemahatau kondisi kronis, seperti penyakit paru obstruktif kronik (PPOK). Gejala infeksi paru-paru bervariasi dari ringan hingga berat,tergantung pada beberapa faktor, termasuk usia dan kondisi kesehatan.Gejala yang ditimbulkan juga tergantung padapenyebab infeksi, apakah disebabkan oleh virus, bakteri, atau jamur. Gejalanya mungkin mirip dengan pilek atau flu tetapicenderung bertahan lebih lama. Simak 10 gejala infeksi paru-paru berikut.</p><h4 class="fs-5">Batuk dengan lendir kental</h4><p class="text-justify fs-6 mt-2">Batuk membantu membersihkan tubuh dari lendir yang dihasilkan dari peradangan saluran udara danparu-paru. Lendir ini mungkin juga mengandung darah. Penderita bronkitis atau pneumonia akan mengalami batuk yang menghasilkan lendir kental dan mungkin berwarna berbeda, seperti jernih, putih, hijau, dan abu-abu kekuningan. Batuk dapatbertahan selama beberapa minggu, bahkan setelah gejala lain membaik.</p><h4 class="fs-5">Nyeri dada</h4><p class="text-justify fs-6 mt-2">Nyeri dada yang disebabkan infeksi paru-paru sering digambarkan sebagai rasa sakit seperti ditusuk. Nyeri dada cenderungmemburuk saat batuk atau bernapas dalam-dalam. Terkadang, rasa sakit yang tajam bisa dirasakan di punggung bagiantengah hingga atas.</p><h4 class="fs-5">Demam</h4><p class="text-justify fs-6 mt-2">Demam terjadi saat tubuh mencoba melawan infeksi. Suhu tubuh normal biasanya sekitar 37°C. Jika menderita infeksi paru-parubakteri, demam bisa naik setinggi 40,5°C. Setiap demam tinggi di atas 38,9°C sering menyebabkan banyak gejala lain, sepertiberkeringat, panas dingin, nyeri otot, dehidrasi, sakit kepala, dan lemas. Segera periksa ke dokter jika demam lebih dari 38,9°Catau berlangsung lebih dari tiga hari.</p>',
                'text2' => '<h4 class="fs-5">Badan nyeri</h4> <p class="text-justify fs-6 mt-2">Otot dan punggung mungkin terasa sakit saat mengalami infeksi paru-paru, disebut mialgia. Kadang-kadang terjadi peradanganpada otot-otot yang juga dapat menyebabkan nyeri tubuh ketika mengalami infeksi.</p><h4 class="fs-5">Hidung meler</h4><p class="text-justify fs-6 mt-2">Meler dan gejala mirip flu lain, seperti bersin, sering menyertai infeksi paru-paru seperti bronkitis.</p><h4 class="fs-5">Sesak napas</h4><p class="text-justify fs-6 mt-2">Sesak napas mengganggu aktivitas karena Anda akan kesulitan bernapas. Anda harus segera menemui dokter jika mengalami hal ini.</p><h4 class="fs-5">Merasa Lelah</h4><p class="text-justify fs-6 mt-2">Anda biasanya akan merasa lesu dan lelah saat tubuh melawan infeksi. Perbanyak istirahat sangat penting dalammelawan mikroorganisme tersebut.</p><h4 class="fs-5">Napas berbunyi</h4><p class="text-justify fs-6 mt-2">Saat bernapas, Anda mungkin mendengar suara siulan bernada tinggi yang dikenal sebagai mengi. Suara ini muncul akibat saluranudara menyempit atau peradangan.</p><h4 class="fs-5">Kulit dan bibir membiru</h4> <p class="text-justify fs-6 mt-2">Bibir atau kuku yang membiru menjadi tanda Anda kekurangan oksigen. Segera konsultasi ke dokter jika mengalami gejala ini.</p><h4 class="fs-5">Bunyi gemeretak di paru-paru</h4><p class="text-justify fs-6 mt-2">Salah satu tanda infeksi paru-paru adalah suara berderak di dasar paru-paru, juga dikenal sebagai bibasilar crackles. Suara ini dapatdidengar menggunakan stetoskop. </p>'
            ],
            [
                'judulInformasi' => 'Supaya Jalan Kaki Tambah Bermanfaat untuk Tubuh Tingkatkan dengan 3 Latihan Ini',
                'excerptJudul' => 'Supaya Jalan Kaki Tambah Bermanfaat untuk Tubuh Tingkatkan dengan 3 Latihan Ini',
                'excerptBody' => 'Berjalan kaki mungkin terlihat mudah dibanding olahraga lagi. Tapi manfaatnya sangat luas, menurut pelatih Onyx Juliet Root.',
                'text1' => '<p class="text-justify fs-6 mt-2">Berjalan kaki mungkin terlihat mudah dibanding olahraga lagi. Tapi manfaatnya sangat luas, menurut pelatih Onyx Juliet Root. Berjalan meningkatkan daya tahan dan kekuatan otot, meningkatkan tingkat energi, meningkatkan mood dan kognisi, dan bahkan memperkuat sistem kekebalan tubuh.</p><p class="text-justify fs-6 mt-2">Mengingat semua manfaatnya, tidak mengherankan bahwa berjalan adalah salah satu latihan terbaik yang dapat Anda lakukan untuk umur panjang, dan bentuk aktivitas fisik favorit di Blue Zones, di mana orang-orang yang hidup paling lama di planet ini tinggal. Di area ini Anda akan menemukan bahwa berjalan adalah bagian integral dari kehidupan sehari-hari.</p><p class="text-justify fs-6 mt-2">Jalan kaki dengan sendirinya dianggap sebagai latihan menahan beban. Jadi, meskipun bukan latihan kekuatan, ini membantu membangun daya tahan otot karena tubuh Anda harus menopang beratnya sendiri. Jika Anda ingin menambahkan lebih banyak manfaat untuk jalan-jalan Anda berikutnya, cobalah salah satu latihan jalan kaki ini dari Root.</p><p class="text-justify fs-6 mt-2">3 latihan berjalan kaki untuk meningkatkan level jalan Anda berikutnya</p>',
                'text2' => '<h4 class="fs-5">1. Bawa beberapa beban</h4><p class="text-justify fs-6 mt-2">"Berjalan sudah melatih inti dan seluruh tubuh bagian bawah Anda, tetapi menambahkan beberapa beban dapat meningkatkan dan melatih tubuh bagian atas Anda, serta meningkatkan detak jantung Anda," kata Root, seperti dilansir dari laman Well and Good. Ada banyak pilihan untuk dipilih di sini, tetapi karena berjalan adalah aktivitas ketahanan otot, tetaplah dengan beban yang lebih ringan yang dapat Anda bawa untuk jangka panjang.</p><h4 class="fs-5">2. Beristirahatlah untuk melakukan pekerjaan mobilitas</h4><p class="text-justify fs-6 mt-2">"Saya suka menggabungkan latihan mobilitas ke dalam rutinitas berjalan," kata Root. "Anda dapat melakukan tendangan hamstring, peregangan quad bergantian, lingkaran pinggul, dan ayunan lengan untuk mendapatkan lebih banyak fleksibilitas dan fungsi di seluruh tubuh Anda."</p><h4 class="fs-5">3. Tambahkan gerakan berat badan</h4><p class="text-justify fs-6 mt-2">Root juga merekomendasikan untuk menggabungkan gerakan berat badan, seperti lunge dan squat, untuk menambah intensitas jalan kaki Anda. Berhati-hatilah dengan gerakan Anda sehingga Anda tidak memasukkannya ke dalam formulir Anda untuk meningkatkan manfaatnya dan mengurangi peningkatan cedera Anda. </p>'
            ],
        ];

        \DB::table('informasi')->insert($informasi);
    }
}
